name: Terry Molloy
favicon: null
layout_spectrum: 0.91701
typography_spectrum: 0.68286
title: 'The Where, When & Who'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000001'
    - '#a24901'
    - '#d6783c'
    - '#f7e6cf'
    - '#455636'
  brandStrength: 0.75
  lightness: 0.125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
