name: Terry Molloy
favicon: null
layout_spectrum: 0.09860450006090105
typography_spectrum: 0.8398616292979568
title: 'The Where, When & Who'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000001'
    - '#a24901'
    - '#d6783c'
    - '#f7e6cf'
    - '#455636'
  brandStrength: 0.75
  lightness: 0.4340267579536885
  saturation: 0.08068642439320683
  rhythmicContrast: 0.26272913278080523
purpose: []
